name: Build and Tag Artifacts

on:
 push:
  branches:
   - master

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout code
    uses: actions/checkout@v2

   - name: Increment Version and Tag Artifact
    run: |
     # Read the current version from the repository tags, or default to 1.0 if no tags are found.
     LAST_VERSION=$(git describe --tags --abbrev=0 || echo "1.0")

     # Increment the version
     NEW_VERSION=$((LAST_VERSION + 1))

     # Create a new tag with the incremented version
     NEW_TAG="v.${NEW_VERSION}"

     # Push the new tag to the repository
     git tag "$NEW_TAG"
     git push origin "$NEW_TAG"

     # Use the incremented version (NEW_TAG) for your artifact tagging process
     echo "Artifact version: $NEW_TAG"
