name: Build and Tag Artifacts

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Increment Version and Tag Artifact
        run: |
          # Read the current version from the repository tags
          LAST_TAG=$(git describe --tags --abbrev=0)
          
          # Extract the numeric part of the last tag
          LAST_VERSION=${LAST_TAG##v}

          # Increment the version
          NEW_VERSION=$((LAST_VERSION + 1))

          # Create a new tag with the incremented version
          NEW_TAG="v.${NEW_VERSION}"

          # Push the new tag to the repository
          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"

          # Use the incremented version (NEW_TAG) for your artifact tagging process
          echo "Artifact version: $NEW_TAG"
