name: SonarQube analysis

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11' # You can specify the Java version required by SonarQube

      - name: Authenticate
        uses: SonarSource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          
      - name: Run SonarScanner    
        run: |
          # Replace these variables with your actual values
          PROJECT_KEY="new-python"
          PROJECT_NAME="new-python"
          SCANNER_HOME="/var/lib/jenkins/tools/hudson.plugins.sonar.SonarRunnerInstallation/sonar-scanner"
          
          # Run the SonarScanner command
          $SCANNER_HOME/bin/sonar-scanner \
            -Dsonar.projectKey="$PROJECT_KEY" \
            -Dsonar.projectName="$PROJECT_NAME" \
            # Add any additional SonarScanner options here
